title: "Via Browser Hub"
description: "Userscripts & Filterlists for Via Browser"
url: "https://limon.github.io"
baseurl: "/via-Userscripts"   # change if your repo name is different
remote_theme: jekyll-garden/jekyll-garden.github.io

plugins:
  - jekyll-feed
  - jekyll-seo-tag
