# Site settings
title: "Via Browser Hub"
description: "Curated Userscripts & Filterlists for Via Browser — fast, private, and optimized."
url: "https://noushad.qzz.io"   # your custom domain
baseurl: ""                     # empty since site is at root of domain

# Theme (official GitHub Pages theme)
theme: jekyll-theme-slate

# Menu (manual links in header/footer if needed)
menu:
  - title: "Userscripts"
    url: "/Userscripts"
  - title: "Filterlists"
    url: "/Filters"
  - title: "About"
    url: "/about"

# Footer
footer:
  copyright: "© 2025 Noushad"
  credits:
    enabled: true
    text: "Powered by GitHub Pages"

# Plugins (all supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
